### ISSUE TITLE
브랜치에서 작업이 많아질 경우 task 브랜치 활용

### ISSUE THREAD

**Issue by damiano1027** [BCSDLab/KOIN_API#112]
# 브랜치에서 작업이 많아질 경우 task 브랜치 활용
- 현재는 `develop` 브랜치에서 `feature/xx-xx-xx`, `refactor/xx-xx-xx` 등의 브랜치를 따서 작업 진행후 `develop` 브랜치로 PR를 하는 방식이다.
- 그런데 만약 해당 브랜치에서 수행되는 작업이 많아지게 되면 reviewer가 보기에는 가독성이 크게 떨어지고 리뷰를 하기 힘들다.
- 따라서 앞으로는 브랜치를 따게 되면, 해당 브랜치에서 어떠한 작업들이 이루어질지 정리해보고 다음과 같이 진행한다.
   - 작은 작업이라면 그냥 진행
   - 큰 작업이라면 task별로 나눠놓고 진행
      - task 브랜치에서의 작업이 끝날때마다 PR을 날린다.

- 예시
   - `feature/upload-api`
      - `task/create-dto`
      - `task/set-aws-s3`
      - `task/write-service-logic`
      - ...

- 현재 `shop-menu-renewal` 브랜치와 `user-table-renewal`의 경우는 위 컨벤션에 맞지 않게 작업이 많이 진행되었기 때문에, 이것을 제외하고 이후부터는 해당 규칙에 맞게 작업한다.

**Comment by Invidam** [comment]
작업이 많다는 걸 깨달을 때면 브랜치를 나누기 이미 늦을 것 같아서,
작업 들어가기 전에 task를 어떻게 나눌지 계획을 미리 세워야 할 것 같아요. 👶

**Comment by damiano1027** [comment]
> 작업이 많다는 걸 깨달을 때면 브랜치를 나누기 이미 늦을 것 같아서, 작업 들어가기 전에 task를 어떻게 나눌지 계획을 미리 세워야 할 것 같아요. 👶

그게 좋을것 같네요. 
관련해서 내용 수정해놓겠습니다.
