### ISSUE TITLE
배포시 순서

### ISSUE THREAD

**Issue by damiano1027** [BCSDLab/KOIN_API#139]
production이라고 가정

1. 1차 배포
  - pull request merge
  - jenkins에서 배포

2. 상점 데이터 마이그레이션
  - `parse.py` 실행
     - ec2 서버에서 `python3 /home/ubuntu/KOIN_BATCH/crawling/parse.py`

3. 남은 flyway sql 파일들 추가
  - 프로젝트에 추가 후 pull request
 
4. 2차 배포
  - pull request merge
  - jenkins에서 배포

이 과정들은 stage에서 반드시 테스트가 선행되어야 한다.

**Comment by Invidam** [comment]
table drop을 진행하지 않으면 2차배포 과정을 나누지 아니해도 된다.

**Comment by Choi-JJunho** [comment]
wiki로 이관

- https://github.com/BCSDLab/KOIN_API/wiki/%EB%B0%B0%ED%8F%AC-%EC%88%9C%EC%84%9C
