### ISSUE TITLE
어드민 사장님 목록 API

### ISSUE THREAD

**Issue by Invidam** [BCSDLab/KOIN_API#219]
사장님 목록을 조회

- [x] 일반 사장님 목록
- [x] 승인할 사장님 목록
  - [x] 요청한 상점 ID, 이름도 제공함.
- [x] 가입 완료된 사장님 목록
- [x] 응답하는 사장님 정보에 (연락처)도 추가되었는지 확인

**Comment by Invidam** [comment]
@tmdgus1715 어느정도 진행되고 있나요??

**Comment by tmdgus1715** [comment]
good
