### ISSUE TITLE
사장님 요청시 shop_id가 없는 현상

### ISSUE THREAD

**Issue by johnny19991006** [BCSDLab/KOIN_API#315]
## Description
![image](https://github.com/BCSDLab/KOIN_API/assets/79901434/417d03f1-a4e6-47a7-a937-6acb5953d076)

![image](https://github.com/BCSDLab/KOIN_API/assets/79901434/d641e3b4-5833-41e0-8426-a946cd15fbf6)
원인)
사장님이 인증되지 않은상태에서는 shop에 owner가 할당되어있지 않음.
어드민이 owner를 조회하는 시점은 인증되지 않은 시점
findShopByOwnerId로 조회하면 상점이 아무것도 안나옴
## Remark

추가 조치가 필요한 사항)
shop에 ownerId가 이미 존재하는 경우 회원가입에서 해당 shop 선택 못하게 막아야한다.
승인 전에는 DB에 쓰기를 수행할 수 없으므로 Redis에 임시 저장해야한다.
tempShop을 물고있는다.
승인 후에는 tempShop 정보에 따라 DB에 업데이트한다.
tempShop.Id == null인 경우
shopName을 기준으로 shop 생성
ownerId 할당
tempShop.Id != null인 경우
해당 shop의 ownerId를 승인한 owner의 id로 업데이트
name은 무시

**Comment by Choi-JJunho** [comment]
- https://bcsdlab.slack.com/archives/CE3MQCQNA/p1705577518952019
