### ISSUE TITLE
사장님 회원가입시 파일크기 넘어갈경우 에러

### ISSUE THREAD

**Issue by johnny19991006** [BCSDLab/KOIN_API#316]
## Description
사장님 회원가입시, 파일크기가 넘어가면 다시 파일 등록하고 등록시 이전에 작성한 데이터가 사라진다.

**Comment by Choi-JJunho** [comment]
- https://bcsdlab.slack.com/archives/CE3MQCQNA/p1705573678744969

**Comment by Choi-JJunho** [comment]
프론트엔드 상태관리 이슈로 파악
