### ISSUE TITLE
사장님 요청시 attachments_id 여부

### ISSUE THREAD

**Issue by johnny19991006** [BCSDLab/KOIN_API#319]
## Description
![image](https://github.com/BCSDLab/KOIN_API/assets/79901434/28e239cf-eee8-4032-b0bb-c06052cc1abb)
사장님 요청시 attachments_id를 볼 방법이 없다
image_urls로 변경요망
## Task List

- [ ] Task1

**Comment by Choi-JJunho** [comment]
- https://bcsdlab.slack.com/archives/CE3MQCQNA/p1705577743838389

**Comment by Choi-JJunho** [comment]
https://admin.stage.koreatech.in/manager-request/4534
