### ISSUE TITLE
카테고리 id 1번이 전체보기가 되는 경우

### ISSUE THREAD

**Issue by johnny19991006** [BCSDLab/KOIN_API#320]
## Description

![image](https://github.com/BCSDLab/KOIN_API/assets/79901434/260967de-c1a3-493b-b71d-1ca058a22b3a)
문제)
조회 시 category=1 이 기본적으로 검색조건에 들어가있음
해결방안)
상점 생성 시 해당 상점에 전체보기라는 카테고리를 적용해줘야한다.

**Comment by Choi-JJunho** [comment]
- https://bcsdlab.slack.com/archives/CE3MQCQNA/p1705579317582949
